# Generated by Django 5.1.2 on 2024-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home & Kitchen'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('health', 'Health & Beauty'), ('automotive', 'Automotive'), ('groceries', 'Groceries'), ('office', 'Office Supplies')], default='electronics', max_length=50),
        ),
    ]
